name: Build Documentation
description: 'Build Documentation.'

runs:
  using: composite
  steps:
    - name: Build Documentation
      shell: bash
      run: |
        phpdoc \
          -d src \
          -t "docs" \
          --ignore '**/Impl/' \
          --ignore-tags psalm-param \
          --ignore-tags psalm-var \
          --ignore-tags psalm-return \
          --visibility public \
          --defaultpackagename "LaunchDarkly" \
          --title "LaunchDarkly PHP SDK phpredis integration 2.0.0" # x-release-please-version
