version: 2.1

workflows:
  workflow:
    jobs:
      - linux-test:
          name: PHP 7.3
          docker-image: cimg/php:7.3
      - linux-test:
          name: PHP 7.4
          docker-image: cimg/php:7.4

jobs:
  linux-test:
    parameters:
      docker-image:
        type: string

    docker:
      - image: <<parameters.docker-image>>
      - image: redis

    steps:
      - checkout
      - run:
          name: install phpredis
          command: |
            sudo apt-get -q update
            sudo apt-get -y install php-redis
            sudo echo "extension=phpredis.so" >> $(php -r 'echo get_cfg_var("cfg_file_path");')
      - run:
          name: install dependencies
          command: composer install --no-progress
      - run: mkdir -p ./phpunit
      - run:
          name: run tests
          command: php vendor/bin/phpunit
      - store_test_results:
          path: ./phpunit
      - store_artifacts:
          path: ./phpunit
