publications:
  - url: https://packagist.org/packages/launchdarkly/server-sdk-redis-phpredis
    description: Packagist

circleci:
  linux:
    image: ldcircleci/php-sdk-release:1  # built in sdks-ci-docker project, contains PHP 7.3 + phpDocumentor

documentation:
  githubPages: true
  title: LaunchDarkly PHP SDK phpredis integration
