version: 2

publications:
  - url: https://packagist.org/packages/launchdarkly/server-sdk-redis-phpredis
    description: Packagist

jobs:
  - template:
      name: php
      skip:
        - test  # don't try to run unit tests in the Releaser environment, since they require a database

documentation:
  gitHubPages: true
  title: LaunchDarkly PHP SDK phpredis integration
