version: 2

publications:
  - url: https://packagist.org/packages/launchdarkly/server-sdk-redis-phpredis
    description: Packagist

jobs:
  - template:
      name: php

documentation:
  gitHubPages: true
  title: LaunchDarkly PHP SDK phpredis integration
