version: 2.1

workflows:
  workflow:
    jobs:
      - linux-test:
          name: PHP 7.3
          docker-image: cimg/php:7.3
      - linux-test:
          name: PHP 7.4
          docker-image: cimg/php:7.4
      - linux-test:
          name: PHP 8.0
          docker-image: cimg/php:8.0

jobs:
  linux-test:
    parameters:
      docker-image:
        type: string

    docker:
      - image: <<parameters.docker-image>>

    steps:
      - checkout
      - run:
          name: install dependencies
          command: composer install --no-progress
      - run: mkdir -p ./phpunit
      - run:
          name: run tests
          command: php vendor/bin/phpunit
      - store_test_results:
          path: ./phpunit
      - store_artifacts:
          path: ./phpunit
