name: CI Workflow
description: 'Shared CI workflow.'
inputs:
  php-version:
    description: 'Which version of PHP should we setup?'
    required: false
    default: 7.4
  use-lowest-dependencies:
    description: 'Should we prefer the lowest dependency version?'
    type: boolean
    required: false
    default: false
  shared-test-version:
    description: 'Which version of the shared test package should we required'
    required: false
    default: 4.x-dev
  token:
    description: 'Token used to prevent composer rate limiting'
    required: true

runs:
  using: composite
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@e6f75134d35752277f093989e72e140eaa222f35
      with:
        php-version: ${{ inputs.php-version }}
        tools: phpdoc:3.1.2
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Install dependencies
      shell: bash
      run: composer install --no-progress

    - name: Require appropriate shared tests package
      shell: bash
      run: composer require --dev 'launchdarkly/server-sdk-shared-tests:${{ inputs.shared-test-version }}'

    - name: Downgrade to lowest versions
      if: ${{ inputs.use-lowest-dependencies }}
      shell: bash
      run: composer update --prefer-lowest --prefer-stable

    - name: Run unit tests
      shell: bash
      run: ./vendor/bin/phpunit
