name: Run Release Please

on:
  push:
    branches:
      - 1.x

jobs:
  release-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Contents and pull-requests are for release-please to make releases.
      pull-requests: write

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: googleapis/release-please-action@v4
        id: release

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          fetch-depth: 0 # If you only need the current version keep this.

      - name: Build and Test
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: ./.github/actions/ci
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build documentation
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: ./.github/actions/build-docs

      - uses: ./.github/actions/publish-docs
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          token: ${{secrets.GITHUB_TOKEN}}
